image: maven:3.6.3-jdk-14

#dependencies cache
# cache:
 # paths:
  #  - .m2/repository

stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  tags:
    - Shell
  script:
    - echo "static analysis"
    

unittest:
  stage: Test
  tags:
    - Shell
  script:
    - echo "test"
    

deploy:
  stage: Deploy
  tags:
    - Shell
  script:
    - echo "deploy"
    
