image: maven:latest

#dependencies cache
cache:
  paths:
    - .m2/repository

stages:
  - shared_runner_test
  - docker_test
#  - project_build
#  - project_test
  - build
  - test
  - deploy

#project_build:
#  stage: project_build
#  tags:
#    - Shell
#  script:
#      - mvn clean compile -V -e -f pom.xml

#project_test:
#  stage: project_test
#  tags:
#    - Shell
#  script:
#      - mvn install -V -e -f pom.xml

shared_runner_test:
  stage: shared_runner_test
  tags: 
    - shell
  script: 
    - echo "Shared Runner Test"


docker_test:
  stage: docker_test
  tags: 
    - docker
  script: 
    - echo "Shared Docker Running"

build:
  stage: build
  tags:
    - shell
  script:
    - echo "Local Runner"
    - mvn -verify
    - echo "Building Project"
    - mkdir build
    - touch build/info.txt
    - mvn clean compile -V -e -f pom.xml
  artifacts:
    paths:
      - build/


test:
  stage: test
  tags:
    - shell
  script:
    - mvn install -V -e -f pom.xml
    - echo "Starting Testing"
    - echo "Test report is below:"
    - mvn verify -e -f pom.xml
    # - mvn test - Issues with the mvn test command
  artifacts:
    when: always
    paths:
    #  ADD FIle Paths To reports


deploy:
  stage: deploy
  tags:
    - shell
  script:
    - echo "deploy"
    
