image: maven:latest

#dependencies cache
cache:
  paths:
    - .m2/repository

stages:
  - docker_test
  - shell_build
  - shell_test
  - docker_build
  - docker_test
  - deploy

shell_build:
  stage: shell_build
  tags:
    - shell
  script:
    - echo "Shared Runner Shell Build"
    - mvn -verify
    - echo "Building Project"
    - mkdir build
    - touch build/info.txt
    - mvn clean compile -V -e -f pom.xml
  artifacts:
    paths:
      - build/

docker_build:
  stage: docker_build
  tags:
    - docker
  script:
    - echo "Shared Runner Docker Build"
#    - mvn -verify
#    - echo "Building Project"
#    - mkdir build
#    - touch build/info.txt
#    - mvn clean compile -V -e -f pom.xml
#  artifacts:
#    paths:
#      - build/

shell_test:
  stage: shell_test
  tags:
    - shell
  script:
    - echo "Shared Runner Shell Test"
    - mvn install -V -e -f pom.xml
    - echo "Starting Testing"
    - echo "Test report is below:"
    - mvn verify -e -f pom.xml
    # - mvn test - Issues with the mvn test command
  artifacts:
    when: always
    paths:
    #  ADD FIle Paths To reports


docker_test:
  stage: shell_test
  tags:
    - docker
  script:
    - echo "Shared Runner Shell Test"
#    - mvn install -V -e -f pom.xml
#    - echo "Starting Testing"
#    - echo "Test report is below:"
#    - mvn verify -e -f pom.xml
#    # - mvn test - Issues with the mvn test command
#  artifacts:
#    when: always
#    paths:
#    #  ADD FIle Paths To reports


deploy:
  stage: deploy
  tags:
    - shell
  script:
    - echo "deploy"
    
