image: maven:latest-jdk-14

#dependencies cache
cache:
  paths:
    - .m2/repository

stages:
  - project_build
  - project_test
  - build
  - test
  - deploy

project_build
  stage: project_build
    script:
      - mvn clean compile -V -e -f pom.xml

project_test
  stage: project_test
    script:
      - mvn install -V -e -f pom.xml

build:
  stage: ubild
  tags:
    - Shell
  script:
    - mvn -verify
    - echo "Building Project"
    - mkdir build
    - touch build/info.txt
    - mvn clean compile -V -e -f pom.xml
  artifacts:
    paths:
      - build/


test:
  stage: test
  tags:
    - Shell
  script:
    - echo "Starting Testing"
    - echo "Test report is below:"
    - mvn verify -e -f pom.xml
  artifacts:
    when: always
    paths:
    # <ADD FIle Paths To reports>


deploy:
  stage: Deploy
  tags:
    - Shell
  script:
    - echo "deploy"
    
